name: machine-learning-book
channels:
  - conda-forge
  - defaults
  - torch
dependencies:
  - numpy=1.21.2
  - pandas=1.3.2
  - scipy=1.7.0
  - python=3.9
  - matplotlib=3.4.3
  - scikit-learn=1.0
  - jupyterlab>=3.4.4
  - pytorch=2.1.2=py3.9_0
  - torchdata=0.7.1=py39
  - torchtext=0.16.2=py39
  - torchvision=0.16.2=py39_cpu
